"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Nav } from "@/components/nav";
import { saveStory } from "@/lib/storage";
import type { FounderStory } from "@/lib/types";

export default function CreatePage() {
  const router = useRouter();
  const [f, setF] = useState<Partial<FounderStory>>({ founderName: "", founderRole: "", productName: "", productUrl: "", productDescription: "" });
  const set = (k: keyof FounderStory, v: string) => setF((s) => ({ ...s, [k]: v }));
  const submit = (e: React.FormEvent) => { e.preventDefault(); const id = crypto.randomUUID(); const story: FounderStory = { id, createdAt: new Date().toISOString(), founderName: f.founderName || "Alex Chen", founderRole: f.founderRole || "Solo founder", founderAvatarUrl: f.founderAvatarUrl || "", productName: f.productName || "Luna", productUrl: f.productUrl || "https://luna.app", productDescription: f.productDescription || "AI workspace for solo builders.", productScreenshotUrl: f.productScreenshotUrl || "", monthOrLaunch: f.monthOrLaunch || "March 2026", revenue: f.revenue || "$10k MRR", users: f.users || "2,843", launches: f.launches || "2", biggestWin: f.biggestWin || "Shipped onboarding v2 and doubled activation.", biggestFail: f.biggestFail || "Delayed docs and support volume spiked.", biggestLesson: f.biggestLesson || "Simple onboarding beats flexible onboarding.", topChannel: f.topChannel || "Product Hunt", nextGoal: f.nextGoal || "Reach 4k active users.", founderQuote: f.founderQuote || "Build small, ship weekly, learn fast." }; saveStory(story); router.push(`/wrapped/${id}`); };
  const field = (name: keyof FounderStory, label: string, ph: string, area?: boolean) => <label className="block"><span className="mb-2 block text-sm font-semibold text-brand-text">{label}</span>{area ? <textarea placeholder={ph} className="w-full rounded-2xl border border-brand-border bg-white p-3" value={(f[name] as string) || ""} onChange={(e)=>set(name,e.target.value)} /> : <input placeholder={ph} className="w-full rounded-2xl border border-brand-border bg-white p-3" value={(f[name] as string) || ""} onChange={(e)=>set(name,e.target.value)} />}</label>;
  return <main className="pb-16"><Nav /><div className="mx-auto mt-8 max-w-4xl px-6"><h1 className="heading text-5xl">Create your FounderWrapped</h1><p className="text-brand-textSoft">Turn your month into a story worth sharing.</p><form onSubmit={submit} className="mt-6 space-y-8"><section className="fw-card"><h2 className="heading text-2xl">1. Founder</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{field("founderName","Founder name","Alex Chen")}{field("founderRole","Founder role","Solo founder")}{field("founderAvatarUrl","Founder avatar URL","https://...")}</div></section><section className="fw-card"><h2 className="heading text-2xl">2. Product</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{field("productName","Product name","Luna")}{field("productUrl","Product URL","https://luna.so")}{field("productDescription","Product description","AI workspace for indie founders.",true)}{field("productScreenshotUrl","Screenshot URL","https://...")}</div></section><section className="fw-card"><h2 className="heading text-2xl">3. Progress</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{field("monthOrLaunch","Month/Launch","March 2026")}{field("revenue","Revenue","$10k MRR")}{field("users","Users","2,843")}{field("launches","Launches","2")}{field("topChannel","Top channel","Product Hunt")}</div></section><section className="fw-card"><h2 className="heading text-2xl">4. Story</h2><div className="mt-4 grid gap-4">{field("biggestWin","Biggest win","Best conversion day after onboarding changes.",true)}{field("biggestFail","Biggest fail","Overbuilt features without demand.",true)}{field("biggestLesson","Biggest lesson","Ship smaller and talk to users weekly.",true)}{field("nextGoal","Next goal","Reach 5k users.")}{field("founderQuote","Founder quote","Small founders deserve big distribution.")}</div></section><button className="fw-button-primary w-full sm:w-auto">Generate wrapped page</button></form></div></main>;
}
